import { v4 as uuid } from "uuid";
import { img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16, img17, img18, img19, img20, img21, img22, img23, img24 } from "../../assets/images/productImages";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    gender: 'Men',
    title: "Cashmere crewneck sweater",
    price: "1300",
    collection: "Trending Collection",
    clothCategory: "Knitted",
    clothMaterial: "Flannel",
    fillHeart: false,
    inBag: false,
    rating: 4,
    qty: 1,
    image1: img1
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: "Saint Germain fitted pants",
    price: "640",
    collection: "Botique Collection",
    clothCategory: "Polos",
    clothMaterial: "Linen",
    fillHeart: false,
    inBag: false,
    rating: 4,
    qty: 1,
    image1: img2
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: "Reversible cotton ribbed Jacket",
    price: "2150",
    collection: "Summer Collection",
    clothCategory: "Jacket",
    clothMaterial: "Cotton",
    fillHeart: false,
    inBag: false,
    rating: 3,
    qty: 1,
    image1: img3
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: "Vamp Swinsuit",
    price: "425",
    collection: "Summer Collection",
    clothCategory: "Beachwear",
    clothMaterial: "Elastane",
    fillHeart: false,
    inBag: false,
    rating: 5,
    qty: 1,
    image1: img4
  },
  {
    _id: uuid(),
    gender: 'Women',
    title: "Micro print T-Shirt",
    price: "765",
    collection: "New Collection",
    clothCategory: "Polos",
    clothMaterial: "Cotton",
    fillHeart: false,
    inBag: false,
    rating: 3,
    qty: 1,
    image1: img5
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: "Ebroidred Striped Shirt",
    price: "460",
    collection: "Summer Collection",
    clothCategory: "Shirts",
    clothMaterial: "Linen",
    fillHeart: false,
    inBag: false,
    rating: 5,
    qty: 1,
    image1: img6
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: '"H Etrivire" T-Shirt',
    price: "720",
    collection: "New Collection",
    clothCategory: "Polos",
    clothMaterial: "Cotton",
    fillHeart: false,
    inBag: false,
    rating: 2,
    qty: 1,
    image1: img7
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: "Embroidered Buttoned Polo",
    price: "320",
    collection: "New Collection",
    clothCategory: "Polos",
    clothMaterial: "Cotton",
    fillHeart: false,
    inBag: false,
    rating: 3,
    qty: 1,
    image1: img8
  },
  {
    _id: uuid(),
    gender: 'Women',
    title: '"H Round" BRA',
    price: "2310",
    collection: "Summer Collection",
    clothCategory: "Beachware",
    clothMaterial: "Cotton",
    fillHeart: false,
    inBag: false,
    rating: 5,
    qty: 1,
    image1: img9
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: '"Moress Gourmette" boxy fit Shirt',
    price: "1330",
    collection: "Summer Collection",
    clothCategory: "Shirts",
    clothMaterial: "Linen",
    fillHeart: false,
    inBag: false,
    rating: 4,
    qty: 1,
    image1: img10
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: "Reversible rib trim jacket",
    price: "1460",
    collection: "New Collection",
    clothCategory: "Jacket",
    clothMaterial: "Elastane",
    fillHeart: false,
    inBag: false,
    rating: 4,
    qty: 1,
    image1: img11
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: "Collerless boxy fit Shirt",
    price: "500",
    collection: "New Collection",
    clothCategory: "Shirts",
    clothMaterial: "Linen",
    fillHeart: false,
    inBag: false,
    rating: 4,
    qty: 1,
    image1: img12
  },
  {
    _id: uuid(),
    gender: 'Women',
    title: "long-sleeve knitted dress",
    price: "1350",
    collection: "New Collection",
    clothCategory: "Knitted",
    clothMaterial: "Flannel",
    fillHeart: false,
    inBag: false,
    rating: 3,
    qty: 1,
    image1: img13
  },
  {
    _id: uuid(),
    gender: 'Wen',
    title: "sleeve twillaine sweater",
    price: "2150",
    collection: "Botique Collection",
    clothCategory: "Knitted",
    clothMaterial: "Flannel",
    fillHeart: false,
    inBag: false,
    rating: 5,
    qty: 1,
    image1: img14
  },
  {
    _id: uuid(),
    gender: 'Women',
    title: "Grala long sleeve sweater",
    price: "760",
    collection: "New Collection",
    clothCategory: "Knitted",
    clothMaterial: "Flannel",
    fillHeart: false,
    inBag: false,
    rating: 5,
    qty: 1,
    image1: img15
  },
  {
    _id: uuid(),
    gender: 'Women',
    title: '"Berlines Bayadere" pareo',
    price: "585",
    collection: "Summer Collection",
    clothCategory: "Beachwear",
    clothMaterial: "Elastane",
    fillHeart: false,
    inBag: false,
    rating: 4,
    qty: 1,
    image1: img16
  },
  {
    _id: uuid(),
    gender: 'Women',
    title: "Vanessa beach bodysuit",
    price: "640",
    collection: "Summer Collection",
    clothCategory: "Beachwear",
    clothMaterial: "Elastane",
    fillHeart: false,
    inBag: false,
    rating: 5,
    qty: 1,
    image1: img17
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: "Venue Swimsuit",
    price: "460",
    collection: "Summer Collection",
    clothCategory: "Beachwear",
    clothMaterial: "Elastane",
    fillHeart: false,
    inBag: false,
    rating: 2,
    qty: 1,
    image1: img18
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: '"Cotes D`ete" crewneck sweater',
    price: "520",
    collection: "Botique Collection",
    clothCategory: "Knitted",
    clothMaterial: "Flannel",
    fillHeart: false,
    inBag: false,
    rating: 3,
    qty: 1,
    image1: img19
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: '"Mouline ombre" crewneck sweater',
    price: "1480",
    collection: "New Collection",
    clothCategory: "Knitted",
    clothMaterial: "Flannel",
    fillHeart: false,
    inBag: false,
    rating: 2,
    qty: 1,
    image1: img20
  },
  {
    _id: uuid(),
    gender: 'Men',
    title: "Reversible rib trim jacket",
    price: "1870",
    collection: "Trending Collection",
    clothCategory: "Jacket",
    clothMaterial: "Elastane",
    fillHeart: false,
    inBag: false,
    rating: 1,
    qty: 1,
    image1: img21
  },
  {
    _id: uuid(),
    gender: 'Women',
    title: "Tarala Shorts",
    price: "650",
    collection: "Trending Collection",
    clothCategory: "Polos",
    clothMaterial: "Cotton",
    fillHeart: false,
    inBag: false,
    rating: 5,
    qty: 1,
    image1: img22
  }
];
